### ISSUE TITLE
Addon Configuration

### ISSUE THREAD

**Issue by messers0** [mapfau/inputstream.mpd#10]
Where do I configure this addon? I can't find it listed in my Kodi GUI and I can't find any files other than the Team Kodi version of the inputstream addon.

**Comment by mapfau** [comment]
hi messers(), 

1) you need lastest kodi nightly build (kodi 17)
2.) addons->settings->user addons->VideoPlayer InputStream->inputstream.mpd

**Comment by messers0** [comment]
Ah I was using an unrelated test build by mistake. When attempting to open a .strm file containing the first example URL (after configuring the addon with the first example configuration URL) I get [this log output](http://pastebin.com/raw/4Wukj3dy).
