### ISSUE TITLE
Help using inputstream with HLS

### ISSUE THREAD

**Issue by eracknaphobia** [mapfau/inputstream.mpd#13]
I am trying to use the new inputstream to improve my NHL & MLB addons. Something the users have been asking for is a way to start a live stream from the beginning. From what I've been told there is a way for me to do this with the newly added inputstream feature. The problem is I am not sure where to even start testing this out. 
If you have any pointers as to where to start on getting this working I would greatly appreciate it. Currently the streams I am passing to kodi are .m3u8 (HLS) files.

Kodi thread that lead me here:
http://forum.kodi.tv/showthread.php?tid=268408&pid=2308692#pid2308692

Thanks

**Comment by mapfau** [comment]
sorry, didn't recognize this post earlier :-(
I'll take a look on the kodi post - I implemented live-stream in inputstream.smoothstream addon, for mpeg dash there was no example so far - I'll take a look on it.

**Comment by mapfau** [comment]
@eracknaphobia should we continue on this?
If so, it would be great if you could provide a manifest file for this.

**Comment by eracknaphobia** [comment]
I can but right now there are no live games. It may be a bit easier if

**Comment by eracknaphobia** [comment]
Here's an example of an archived game. 
[5000_complete-trimmed.m3u8.txt](https://github.com/mapfau/inputstream.mpd/files/332056/5000_complete-trimmed.m3u8.txt)

**Comment by mapfau** [comment]
Sorry, I hoped that there is some underlying mpd / smoothstream, but the m3u format above is something special wich are out of my scope.

One Idea (must be decided from one who understands the m3u file in your prevous post) could be transforming it into mpd / smothstream manifest file and send it to one of the 2 plugins.

If this is not possible, I see only the chance to handle it in addon (python) or maybe ffmpeg can do anything with it.....

**Comment by Alexqw** [comment]
@mapfau Sorry for resuscitating an old, closed issue, but it seems like the best place.

A group of us maintain the Kodi add-on for NFL Game Pass, and it also uses HLS. Unfortunately, I don't have a good idea on the scope of work that would need to be done to get InputStream with HLS working (would an independent addon be needed or can this one be extended?).

I am not much of a C coder, but if manpower around specs, testing, etc is what is needed, then there's quite a few people who'd be interested in helping out to make this happen.

Thanks for your time and all the effort you've put into making this addon happen.

---Alex

**Comment by mapfau** [comment]
Hi Alex,

I'll take a look into HLS, never spend time on it and have no clue how it looks.
Can you point me to an example wich is based on HLS?

Thanx,

markus

**Comment by kaileu** [comment]
The example from @eracknaphobia posted an example its a bit confusing and complicated.

#EXTM3U
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-TARGETDURATION:10
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:0
#EXTINF:10.0,
http://example.com/movie1/fileSequenceA.ts
#EXTINF:10.0,
http://example.com/movie1/fileSequenceB.ts
#EXTINF:10.0,
http://example.com/movie1/fileSequenceC.ts
#EXTINF:9.0,
http://example.com/movie1/fileSequenceD.ts
#EXT-X-ENDLIST

This is a very basic example of one specific bitrate.
The Header of the Manifest is standard after this it tells were the chunk files are this can be absolute or relative. If the single chunks are encrypted there is another tag: #EXT-X-KEY:METHOD=AES-128,URI="https://priv.example.com/key.php?r=52" which tells were the encryption key is stored.

These Single Manifests are encapsulated by a master manifest which point to the single manifests.

EXTM3U
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio",LANGUAGE="eng",NAME="English",AUTOSELECT=YES, \
DEFAULT=YES,URI="eng/prog_index.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio",LANGUAGE="fre",NAME="Français",AUTOSELECT=YES, \
DEFAULT=NO,URI="fre/prog_index.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio",LANGUAGE="sp",NAME="Espanol",AUTOSELECT=YES, \
DEFAULT=NO,URI="sp/prog_index.m3u8"
 
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=195023,CODECS="avc1.42e00a,mp4a.40.2",AUDIO="audio"
lo/prog_index.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=591680,CODECS="avc1.42e01e,mp4a.40.2",AUDIO="audio"
hi/prog_index.m3u8


I hope this summarize it a bit.
https://developer.apple.com/library/ios/technotes/tn2288/_index.html

**Comment by Alexqw** [comment]
@kaileu Couldn't have said it better myself. :-)

@mapfau Apple has some reference examples here: https://developer.apple.com/streaming/examples/

The .m3u8 URLs are easily found in the page's source.

---Alex

**Comment by mapfau** [comment]
I'll take a look at this how it may fit into the existing .mpd source.
My current feeling ist that it could be easier to write an inputstream.hls instead trying to push these things into inputstream.mpd. Pls. don't expect results very early, I'm currently completely overloaded with real life things :-(

**Comment by Alexqw** [comment]
@mapfau Thanks for taking a look into this.

Makes sense that a new inputstream.hls would likely be cleaner and easier.

As for real life, don't worry. We're all allowed to have real lives. :-)

---Alex

**Comment by X-Kent** [comment]
Any news ?

**Comment by awaters1** [comment]
I took a swing at this in my repository https://github.com/awaters1/inputstream.hls.  I am still in the process of testing it but it is nearly feature complete and works very well with my ESPN3 addon.  I have only tested it on my personal Linux machines so I am unsure if it works on Android, Windows, or other Linux machines.

**Comment by aqw** [comment]
@awaters1 /Fantastic/. I don't have time to test it right now, but I just wanted to say "thank you" for taking a whack at this.

---Alex
