### ISSUE TITLE
Howto build inputstream.mpd.so

### ISSUE THREAD

**Issue by thrillfall** [mapfau/inputstream.mpd#18]
I am on raspbian and have installed kodi 17 from pplware repos. I also installed the inputstream.mpd plugin. But i am missing the **inputstream.mpd.so** for actually watching amazon prime via Sandmann Amazon VOD.
How can i build this file? Do i just need to "cmake ."?

**Comment by mapfau** [comment]
Hi, xbmc/docs/README.linux have an example how to build:

.1  Specific addons
    $ make -C tools/depends/target/binary-addons PREFIX=/<system prefix added on step 4.1> ADDONS="inputstream.mpd"

**Comment by thrillfall** [comment]
Thanks for the quick answer:
when i execute that command i get
```
make: Entering directory '/xbmc/tools/depends/target/binary-addons'
make: Nothing to be done for 'all'.
make: Leaving directory '/xbmc/tools/depends/target/binary-addons'
```
Sorry, but i am really new to compiling from source. How do i include your stuff? Do i need to copy the checkout sources from this repo into the xmbc source?

**Comment by mapfau** [comment]
can you pls post the full make command and the folder from where you execute it?

You normally dont have to download anything, this should be done automaticaly by the scripts that comes with kodi.

**Comment by thrillfall** [comment]
i checkout out kodi sources in /xbmc and your repo is in /inputstream.mpd.
I executed `root@station:/xbmc# make -C tools/depends/target/binary-addons PREFIX=/ ADDONS="inputstream.mpd"`

**Comment by mapfau** [comment]
1.) You don't have to checkout the sources from here, the URL of this repository is known from kodi as this repo here is included in the official binary addon repo from kodi. Download should be done automatically (same for pvr addons)

2.) Prefix must be the same you passed to the build step of kodi, as I remember the default is /usr/local, but you must pass it in the make -C.... command correctly.

Git comment windows unfortunately eat characters when not putting things in code section, my initial prefix is not shown as it was expected. Pls. refer to the docs/README.linux file for the prefix.

`$ make -C tools/depends/target/binary-addons PREFIX=/<system prefix added on step 4.1> ADDONS="inputstream.mpd"`, the prefix must be replaced with your valid prefix.
It is assumed, that you already made make install after building kodi.

**Comment by thrillfall** [comment]
I am doing that right now. I thought that i could just compile the addon and move `inputstream.mpd.so` to my existing kodi installation on my rpi2. Unfortunately there is no deb (armhf) available with your plugin.
Thank you so much for helping me on this.

**Comment by mapfau** [comment]
ok, understood
then its a little bit different I'll send you a link for this, mom

**Comment by mapfau** [comment]
[Build instructions binary addons](http://forum.kodi.tv/showthread.php?tid=219166)
This is more meant for developers and you have to copy the generated files after that manually in your kodi folder. Not sure if you really want this, its kind of pain to get all steps together.

inputstream.mpd is generated for various plattforms every night, for that you have to add an ppa to your system repo settings, I dont use it currently, but maybe you can get them going that way:
apt-get install kodi-inputstream-mpd

**Comment by thrillfall** [comment]
Thanks, i'll try that then. I have added `http://pipplware.pplware.pt/pipplware/dists/unstable/armv7/binary` for kodi. This is the only repo that holds kodi 17 builds for arm. Sadly they dont build the inputstream.mpd plugin. So no `apt-get install` for me.

**Comment by mapfau** [comment]
OK, sometimes its easier to build it by oneself, searching for such things cost also enourmeous time. There are several people providing complete OE's, one I know is milhouse who has always working inputstream addons inside his package. Good luck!
