### ISSUE TITLE
Selectable streams

### ISSUE THREAD

**Issue by h0d3nt3uf3l** [mapfau/inputstream.mpd#20]
Hey, we're just talkin about in another git [(Here)](https://github.com/ace20022/xbmc/pull/4#issuecomment-223874682)
Maybe its possible to get all available streams forwarded to ffmpeg. I read that it will probess only the active ones. my thoughts are to enable changing streams while watching a video.
I will  prove this topic later on my pc and give you an update. 

Edit: Tryied to copy the command simply in the windows cmd but sadly there is not enough memory. The command with 22 streams is about 17000 chars long. Think this is too heavy.
Another problem I found with more Streams is that you have to seperate the streams with separate codec, logically :)

What do you think about it?

**Comment by mapfau** [comment]
What is missing, if you pass the mpd manifest file to kodi WITHOUT forcing inputstream.mpd?
ffmpeg should be capable to handle the mpd file and display all streams in kodi.

I don't see any need here that you do any actions here in parsing the mpd. The streams are lying fragmented on the YT server, in general its not simply passing the URL (this could work, but also couldn't).

There are already two libraries doing this stuff: ffmpeg (unencrypted content as yours) or inputstream.mpd (only for .h264, but encrypted). There is no need for you imo for you to do any coding on this part,

Simply use ffmpeg.

**Comment by h0d3nt3uf3l** [comment]
Sure I would use it if it works. Sorry for bothering you but I don't find any documentation to do so. I'm allready a little greenhorn, thought that isn't possible. Searched for the last few days for using ffmpeg directly but can't find anything. I'll keep searching.

**Comment by mapfau** [comment]
But you did it already! Simply pass the URL of the mpd file to kodi like a normal video URL.
Kodi will detect the mime type, and ffmpeg will play it. Thats all.

**Comment by anxdpanic** [comment]
I assumed you meant something else by using ffmpeg as well. That was the first thing I tried anyway, doesn't seem to work. Mime type is properly detected and error probing input format as far as playback. Just re-tested on the latest nightlies (just have to comment out the inputstream properties) and it's still the same. Also just tried a bunch of http://dashif.org/test-vectors/ via strm and again the mime types are correct with same issue on playback. Which as far as I know leaves us with this inputstream add-on as far as unencrypted dash playback as well.

**Comment by mapfau** [comment]
I wouldn't try dashif vectors, these are all different mpd flavours.
I'm quite sure that the YT mpd flavour worked fine (from earlier logs you provided.

There was only an issue with DXVA. Can you pls provide a new log in that you have passed a YT mpd URL to kodi?

**Comment by anxdpanic** [comment]
xbmclogs is having issues atm, http://pastebin.com/Nymj431c

**Comment by mapfau** [comment]
thx, ok, I'll enable "manual stream selection" in inputstream.mpd (to let you select all streams) and will pass the streams muxed to ffmpeg (must be forced by yt plugin, more info if its implemented). You can continue testing with inputstream.mpd, there are many yt videos with h.264.

**Comment by anxdpanic** [comment]
Thank you, appreciate what you're doing/done regardless :+1:
