### ISSUE TITLE
1.1.1 1080p selection bug (works in 1.1.0)

### ISSUE THREAD

**Issue by axbmcuser** [mapfau/inputstream.mpd#21]
1.1.0 worked very good for fixed 1080p hq with settings:
- min/max bandwidth: 100000000/100000000 (100 Mbit)
- max. resolution: 1080p

1.1.1 with same settings:
- min/max bandwidth: 100000000/100000000 (100 Mbit)
- max. resolution: 1080p
- stream selection (new option): auto
falls back to 720p.
Changing "stream selection" to manual restores working 1080p - but clutters the video- and audio-track list with far too many items.

Thanks. Great work!

**Comment by mapfau** [comment]
There will be a fix coming today for 720p with auto.
Pls. wait with further testing for it, thx!

**Comment by axbmcuser** [comment]
Again, thanks!

**Comment by mapfau** [comment]
Ah, forgot to post here, sorry, if your display resolution is ~1080p and you have enough bandwidth, 1080p videos should be played now...

**Comment by axbmcuser** [comment]
No, i'm sorry - forgot to report that i tried 1.1.2 once is was online with final fixes - works without any problems! :)
