### ISSUE TITLE
SegmentTimeline streams will stop during playback

### ISSUE THREAD

**Issue by frankr612** [mapfau/inputstream.mpd#22]
Hi,

I experienced problems with MPD streams containing SegmentedTimeline fields like that:

`<SegmentTimeline>
<S t="0" d="96256" r="2"/>
<S d="95232"/>
<S d="96256" r="2"/>
<S d="95232"/>
<S d="96256" r="2"/>
<S d="95232"/>
<S d="96256" r="2"/>
<S d="95232"/>
<S d="96256" r="2"/>
<S d="95232"/>
<S d="96256" r="2"/>
<S d="95232"/>
<S d="96256" r="2"/>
<S d="95232"/>
<S d="96256" r="2"/>
<S d="95232"/>
<S d="96256" r="2"/>
<S d="95232"/>
<S d="96256" r="2"/>
<S d="95232"/>
<S d="96256" r="2"/>
<S d="95232"/>
<S d="96256" r="2"/>
<S d="95232"/>
<S d="96256" r="2"/>
<S d="95232"/>
<S d="96256" r="2"/>
<S d="95232"/>
<S d="96256" r="2"/>
<S d="95232"/>
<S d="96256" r="2"/>
<S d="95232"/>
<S d="96256" r="2"/>
<S d="95232"/>
<S d="96256" r="2"/>
<S d="95232"/>
<S d="96256" r="2"/>
<S d="95232"/>
<S d="96256" r="2"/>
<S d="95232"/>
<S d="96256" r="2"/>
<S d="95232"/>
<S d="96256" r="2"/>
<S d="95232"/>
<S d="96256" r="2"/>
<S d="95232"/>
<S d="96256" r="2"/>
<S d="95232"/>
<S d="96256" r="2"/>
<S d="95232"/>
<S d="96256" r="2"/>
<S d="95232"/>
<S d="96256" r="2"/>
<S d="95232"/>
<S d="96256" r="2"/>
<S d="95232"/>
<S d="96256" r="2"/>
<S d="95232"/>
<S d="96256" r="2"/>
<S d="95232"/>
<S d="96256" r="2"/>
<S d="95232"/>
<S d="96256" r="2"/>
<S d="95232"/>
<S d="96256" r="2"/>
<S d="95232"/>
<S d="96256" r="2"/>
<S d="95232"/>
<S d="96256" r="2"/>
<S d="95232"/>
<S d="96256" r="2"/>
<S d="95232"/>
<S d="96256" r="2"/>
<S d="95232"/>
<S d="96256" r="2"/>
<S d="95232"/>
<S d="96256" r="2"/>
<S d="95232"/>
<S d="96256" r="2"/>
<S d="95232"/>
<S d="96256" r="2"/>
<S d="95232"/>
<S d="96256" r="2"/>
<S d="95232"/>
<S d="96256" r="2"/>
<S d="95232"/>
<S d="96256" r="2"/>
<S d="95232"/>
<S d="96256" r="2"/>
<S d="95232"/>
<S d="96256" r="2"/>
<S d="95232"/>
<S d="96256" r="2"/>
<S d="95232"/>
<S d="96256" r="2"/>
<S d="95232"/>
<S d="96256" r="2"/>
<S d="95232"/>
<S d="96256" r="2"/>
<S d="95232"/>
<S d="96256" r="2"/>
<S d="95232"/>
<S d="96256" r="2"/>
<S d="95232"/>
<S d="1024"/>
</SegmentTimeline>`

Streams with that kind of segmentation of the audio part seems to play about 75% of the stream then will lead to a freeze. Sometimes audio still keeps playing for a while when the video is already frozen.

Streams with a segmentation (video and audio) like this

`<SegmentTimeline>
<S t="0" d="50" r="207"/>
<S d="1"/>
</SegmentTimeline>`

are playing fine.

**Comment by mapfau** [comment]
I'll check this one, could you pls provide a link to the mpd file?

**Comment by frankr612** [comment]
Sure:

http://damxduspol80-s.akamaihd.net/1007097541/piff-production/content/legacy/80/extremeactiv_6360028_2006/extremeactiv_6360028_2006_uspo0576de20.ism/.mpd

**Comment by mapfau** [comment]
https://github.com/mapfau/inputstream.mpd/commit/d007056ad5bcca9b43887b62f35529ccff316d2e
thx! Could you pls. test? I have no working example for this.......

**Comment by frankr612** [comment]
A first test of an episode which did not work yesterday now plays fine to the end, so it seems it works now. Thanks for fixing!

**Comment by frankr612** [comment]
Another thing that might have to do with the Segmentation stuff is that jumping inside of a stream is very slow. Specially on big steps like 10 minutes its obvious and sometimes make kodi freeze. I'm just not sure if thats a normal behaviour cos it seems inputstream.mpd downloads every segment up to the new position, so it takes the time to download those parts until the video continues. Is that normal or can it be accelerated somehow?

**Comment by mapfau** [comment]
Oh, I thought it was already fixed in one of the previous versions :-(
There has been an similar issue with SegmentTimelines on representation level.

I'll try to find an movie for testing, If I have no luck I would please you for your maxdome account for a couple of hours.....

**Comment by frankr612** [comment]
Sure, just let me know

**Comment by mapfau** [comment]
Can you pls give it another try?

**Comment by frankr612** [comment]
Just tried but it's still the same

**Comment by mapfau** [comment]
You have updated inputstream.mpt with the latest commit here, right?
If so, could you pls send me the addon, the access and the stream you're playing with?
We can use pfau@peak3d.de. Thanks!

**Comment by mapfau** [comment]
solved
