### ISSUE TITLE
Compilation

### ISSUE THREAD

**Issue by rome1983** [mapfau/inputstream.mpd#24]
Can you add compile instructions?

**Comment by mapfau** [comment]
Hi, they are included in the README.xy files in kodi source tree [xbmcsrcroot]/docs
Wich OS are you looking for?

**Comment by rome1983** [comment]
Hi, I'm using Ubuntu.

**Comment by mapfau** [comment]
https://github.com/xbmc/xbmc/blob/master/docs/README.linux#L115

**Comment by rome1983** [comment]
Thanks

**Comment by rome1983** [comment]
I compiled with the instructions and I was able to enable the add-on but kodi crashed when I tried to use the Amazon add-on. I rebooted and kodi crashed on startup.

**Comment by rome1983** [comment]
I got it compiled and kodi doesn't crash but its not finding the decrypter.

**Comment by mapfau** [comment]
You also have to recompile the wvdecrypter from github.com/lberty-developer

**Comment by rome1983** [comment]
I used this before
http://nmacleod.com/public/libreelec/getwidevine.sh

**Comment by mapfau** [comment]
No idea, when he compiled this one the last time - beginning with 1.2.0 there was an API change between inputstream and libssd_wv.

But compiling is really simple, clone the inputstream.mpd, go into the folder wvdevrypter, call cmake . and then make.

**Comment by rome1983** [comment]
Ok Thanks

**Comment by rome1983** [comment]
Success Thank you
