### ISSUE TITLE
KODI (git 49ea098) crashes when trying to install with todays (2016-08-04) inputstream-changes

### ISSUE THREAD

**Issue by axbmcuser** [mapfau/inputstream.mpd#25]
KODI (git 61d6aae) - no crash using latest inputstream.mpd (git ed3eb82)
KODI (git 49ea098) - crash when trying to install inputstream.mpd (git ed3eb82) (if not already installed). If it's already installed crash on boot.

Since we're only talking about todays commits, it could specifically be related to:
https://github.com/xbmc/xbmc/commit/4a67c1632fee7ba5403596fd83b850f2983a8274
https://github.com/xbmc/xbmc/commit/4c05d591b5680ff5ba5f6c4b718ea87872518099
https://github.com/xbmc/xbmc/commit/f9cd1058988bd2bc25381e1cb6e11f9643fa119f

crashlog:
http://pastebin.com/raw/QdhYGSy2

**Comment by FernetMenta** [comment]
you need to compile the addon against current kodi master

**Comment by axbmcuser** [comment]
Ahh - allright. Thank you very much!

**Comment by mapfau** [comment]
thx, @FernetMenta

**Comment by rome1983** [comment]
I compiled against master and still got crash. I'm using the nightly ppa.

**Comment by mapfau** [comment]
Have you removed all build related stuff before? (e.g. git clean -xfd)??

**Comment by rome1983** [comment]
I just copied the files to /usr/lib/kodi/addons, /usr/share/kodi/addons.

**Comment by mapfau** [comment]
can you pls. explain more, what you are compiling and what you are copying?
Do you compile kodi AND addons by yourself? Or only one of those two?

**Comment by rome1983** [comment]
I only compiled the inputstream addon. After compiling I get 2 inputstream.mpd folders. One has libs and the other has resources/addon.xml. I use kodi nightly ppa for kodi, no compiling. I had to uninstall inputstream addon from the ppa because kodi kept crashing on startup.

**Comment by mapfau** [comment]
can you pls git clean-xfd on your local kodi checkout folder?
And then compile addons again? Or did you already cleaned?

**Comment by rome1983** [comment]
No I didn't, will try later.

**Comment by axbmcuser** [comment]
I think this can be closed?
