### ISSUE TITLE
NDR/ZDF streams of the olympics fail

### ISSUE THREAD

**Issue by prof-membrane** [mapfau/inputstream.mpd#26]
Could you take a look at those dash streams (geolocked to germany) of the olympics? The streams have a better quality than the m3u8 alternatives. The ZDF stream offers 50fps, which is nice for a sport event like this.

http://ndrspezial.edgesuite.net/dash/live/923078/ndrspezial_1/spezial_1.mpd
http://zdfolympia6001-i.akamaihd.net/dash/live/253735/olympia/6001.mpd

I can provide you other nonfunctioning stream examples if you are interested.

**Comment by mapfau** [comment]
fixed
