### ISSUE TITLE
Can not open Amazon Prime Video MPDs anymore

### ISSUE THREAD

**Issue by dweinber** [mapfau/inputstream.mpd#27]
I'm using [Sandmann79's Amazon Plugin](https://github.com/Sandmann79/xbmc/tree/master/plugin.video.amazon) together with inputstream.mpd and this used to work great. Since a few days (didn't use it for a few days, so can't exactly say when this started) it doesn't play any stream anymore. Inputstream.mpd is version 1.2.0 from libreelec repo.

I've included the relevant log messages below. The URL is accessible and returns a DASH manifest, so it seems to be related to parsing.

The MPDs look like this [non-working-example.txt](https://github.com/mapfau/inputstream.mpd/files/405099/non-working-example.txt)

```
18:51:48 2967.565674 T:1701000096  NOTICE: [Amazon VOD] http://a585avoddashs3eu-a.akamaihd.net/d/1$AOAGZA014O5RE,B932EB7B/videoquality$720p/ondemand/da16/0473/7138/4c83-af25-41e6d929613c/7c58d25b-51f0-4fd2-ab31-00b4fdea0916_corrected.mpd
18:51:48 2967.865479 T:1962881024  NOTICE: VideoPlayer: Opening: http://a585avoddashs3eu-a.akamaihd.net/d/1$AOAGZA014O5RE,B932EB7B/videoquality$720p/ondemand/da16/0473/7138/4c83-af25-41e6d929613c/7c58d25b-51f0-4fd2-ab31-00b4fdea0916_corrected.mpd
18:51:48 2967.865723 T:1962881024 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
18:51:48 2967.977783 T:1701000096  NOTICE: Creating InputStream
18:51:48 2968.418945 T:1701000096   ERROR: AddOnLog: InputStream MPEG DASH: Could not open / parse mpdURL (http://a585avoddashs3eu-a.akamaihd.net/d/1$AOAGZA014O5RE,B932EB7B/videoquality$720p/ondemand/da16/0473/7138/4c83-af25-41e6d929613c/7c58d25b-51f0-4fd2-ab31-00b4fdea0916_corrected.mpd)
18:51:48 2968.419434 T:1701000096   ERROR: CVideoPlayer::OpenInputStream - error opening [http://a585avoddashs3eu-a.akamaihd.net/d/1$AOAGZA014O5RE,B932EB7B/videoquality$720p/ondemand/da16/0473/7138/4c83-af25-41e6d929613c/7c58d25b-51f0-4fd2-ab31-00b4fdea0916_corrected.mpd]
18:51:48 2968.419434 T:1701000096  NOTICE: CVideoPlayer::OnExit()
18:51:48 2968.420166 T:1962881024   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.amazon-test/?asin=B00MC1SLFG&mode=PlayVideo&name=2+-+Cool+sein&adult=0&trailer=0&selbitrate=0]
```

**Comment by mapfau** [comment]
There has a lot of things changed with versions / api's between inputstream / kodi and decrypter.
If you have autoupdate enabled for inputstream addon you may have got one wich is not compatible.

You can mail the full debug log to me, maybe I can figure out whats wrong.

**Comment by dweinber** [comment]
Will do, thanks. Just the kodi.log or is there anything more specific/verbose?

Guess I'll disable auto update once this is working again...

**Comment by dweinber** [comment]
Seems like the API changes of Kodi broke my system. The addons updated to the new version, but Kodi itself was not updated since June. Updating Kodi and the addons to the latest versions finally did the trick.
