### ISSUE TITLE
Kodi crashes playing following streams

### ISSUE THREAD

**Issue by prof-membrane** [mapfau/inputstream.mpd#31]
http://akamai-progressive.irt.de/arte_uhd_lecorsaire_13min/M4Sv2/V-3840x2160p50_h265_main_bt709_gop100_bit7500k_A1-192k_aac_lc_48k_2ch_ger.mpd
http://akamai-progressive.irt.de/arte_uhd_lecorsaire_13min/M4Sv2/V-3840x2160p50_h265_main_bt709_gop100_bit14M_A1-192k_aac_lc_48k_2ch_ger.mpd

Kodi Beta 1, Inputstream 1.2.6, Windows 7. Unfortunately, I can't test it on my Odroid if it is an issue releated to the codec. The MP4 container plays fine (http://akamai-progressive.irt.de/arte_uhd_lecorsaire_13min/MP4v2/V-3840x2160p50_8bar_h265_main_bt709_gop100_bit7500k_A1-192k_aac_lc_48k_2ch_ger_ffmpeg.mp4). The last log entries are related to audio sync, the add-on manages to download three segments before crashing.

**Comment by mapfau** [comment]
The streams seem to be not valid (at least for me). MOOV defines a single track with id 4, but after 2 fragments with trackid==4 trackid==3 is send. Where are these movies from?

**Comment by prof-membrane** [comment]
The streams are from http://tv-html.irt.de/hbbtv2/arte/uhd_showcase/index.html, an official UHD/HbbTV 2.0 test site of Arte. Arte might be delivering content like this in the near future, but this is just a guess. 

I can't say anything about the properties of the stream itself. I have seen some similar (working) examples from the IRT, with additional audio tracks for various qualities.

**Comment by mapfau** [comment]
at least the first one is now playing with version 1.2.9

**Comment by prof-membrane** [comment]
Nice. That is the only stream I "cared" right now. 

BTW: In the last few weeks, I came across some streams which won't work in Kodi. Most of them are just example streams, unrelated to any real world applications. Do you want such URLs?

**Comment by mapfau** [comment]
Jep, could you pls open one issue for each? then I can close them easily...
