### ISSUE TITLE
Stream doesn't work

### ISSUE THREAD

**Issue by prof-membrane** [mapfau/inputstream.mpd#34]
http://dash.edgesuite.net/dash264/TestCases/1a/sony/SNE_DASH_SD_CASE1A_REVISED.mpd

From the DashIF Reference Player (http://dashif.org/reference/players/javascript/v2.3.0/samples/dash-if-reference-player/index.html). The add-on can't parse the mpd file.

Inputstream.mpd 1.2.9, Kodi 17 Beta 1, Windows 7

I wrote a small add-on which parses all streams of the DashIF Referrence Player. There are multiple streams which won't work in Kodi. Opening issues for each stream is a bit tedious, do you want to try the streams yourself with the add-on?

**Comment by mapfau** [comment]
fixed 1.2.11
